token          = "Basic YWRtaW46YWRtaW4="
admin_user     = "admin"
admin_password = "karce123"
bigip_address  = "10.154.86.118:443"
advanced_shell_user     = "root"
advanced_shell_user_password = "QwXdZKzaeJu5vXLpNrT4"
f5_do_rpm_filename      = "f5-declarative-onboarding-1.37.0-3.noarch"
do_install_dir          = "/var/config/rest/downloads/"