# This module runs the blindfold.sh shell script and generate a stdout output
module "shell_blindfold" {
  source         = "Invicton-Labs/shell-data/external"
  command_unix   = "./scripts/blindfold.sh ${var.lb_cert} ${var.lb_key}"
  fail_on_stderr = true
}

locals {
  description  = "Used to store the output of the blindfold.sh script"
  blindfoldb64 = sensitive(split(" ", module.shell_blindfold.stdout))
}

data "external" "get_certificate_cn" {
  program = ["bash", "-c", "echo \"{\\\"certificate_cn\\\": \\\"$(openssl x509 -noout -subject -in ${var.lb_cert} 2>/dev/null | sed -n 's/.*CN=\\([^/]*\\).*/\\1/p')\\\"}\""]
}

resource "volterra_certificate" "blindfold" {
  name            = replace(data.external.get_certificate_cn.result["certificate_cn"], ".", "-")
  namespace       = var.namespace
  certificate_url = (local.blindfoldb64[0])
  private_key {
    blindfold_secret_info {
      decryption_provider = ""
      store_provider      = ""
      # Use the Blindfold secret generated by the blindfold.sh script
      location = (local.blindfoldb64[1])
    }
    secret_encoding_type = "EncodingNone"
  }
}
