---
- name: Confirm deletion
  pause:
    prompt: "\nAre you sure you want to delete tenant {{ tenant_to_migrate }} and all its content on {{ old_device_address.target.address }}?\n\n
             Do you want to proceed? (yes/no)"
  register: confirm_delete

# Delete old app service if remove_old_app true
- name: ATC POST - delete all AS3 application services in tenant {{ tenant_to_migrate }}
  include_role:
    name: f5devcentral.atc_deploy
  vars:
    atc_service: AS3
    atc_method: POST
    atc_declaration: |
          {
              "class": "AS3",
              "action": "deploy",
              "persist": true,
              "declaration": {
                  "class": "ADC",
                  "schemaVersion": "3.7.0",
                  "id": "delete",
                  "label": "delete",
                  "remark": "delete",
                  "target": {
                      "address": "{{ old_device_address.target.address }}"
                  },
                  "{{ tenant_to_migrate }}": {
                      "class": "Tenant"
                  }
              }
          }
    atc_delay: 15
    atc_retries: 30
  register: atc_AS3_status
  when: confirm_delete.user_input | bool

- name: Cleanup Empty BIG-IQ Application in Dashboard
  include_tasks: "cleanup-bigiq-apps-dashboard.yaml"
  when: confirm_delete.user_input | bool